PRODUCT_VECTORSTORE_COLLECTION_NAME = "products-store"
PRODUCT_VECTORSTORE_INDEX_NAME = "products-retriever"
ORDER_VECTORSTORE_COLLECTION_NAME = "orders-store"
ORDER_VECTORSTORE_INDEX_NAME = "orders-retriever"
